"""Add all loan request columns

Revision ID: 66d566283326
Revises: 
Create Date: 2025-06-20 18:36:42.958403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66d566283326'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('loan_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('married', sa.String(length=3), nullable=True),
    sa.Column('dependents', sa.Integer(), nullable=True),
    sa.Column('education', sa.String(length=20), nullable=True),
    sa.Column('self_employed', sa.String(length=3), nullable=True),
    sa.Column('applicant_income', sa.Float(), nullable=True),
    sa.Column('coapplicant_income', sa.Float(), nullable=True),
    sa.Column('loan_amount', sa.Float(), nullable=True),
    sa.Column('loan_term', sa.Float(), nullable=True),
    sa.Column('credit_history', sa.Float(), nullable=True),
    sa.Column('property_area', sa.String(length=20), nullable=True),
    sa.Column('prediction', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_request')
    op.drop_table('user')
    # ### end Alembic commands ###
